### ISSUE TITLE
Install under Rstudio

### ISSUE THREAD

**Issue by DrNJT** [lixun910/rgeoda#5]
I'm trying to install rgeoda under RStudio 1.3.1093 running R 4.0.3 on Ubuntu 18.04 and get the following error

make: *** No rule to make target 'libgeoda_src/libgeoda.o', needed by 'rgeoda.so'. Stop.
ERROR: compilation failed for package ‘rgeoda’

> devtools::session_info()
─ Session info ───────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 4.0.3 (2020-10-10)
 os       Ubuntu 18.04.5 LTS          
 system   x86_64, linux-gnu           
 ui       X11                         
 language en_GB:en                    
 collate  en_GB.UTF-8                 
 ctype    en_GB.UTF-8                 
 tz       Europe/London               
 date     2020-12-11        

Anything obvious I could check?

**Comment by lixun910** [comment]
@DrNJT Yes, the current rgeoda 0.0.4/3 is only for R 3.6 (if I remember correctly). Now, I am working on getting rgeoda 0.1 into CRAN, so there will be no installation issue. It could take a couple of weeks, and I will post updates here. For a workaround, you can try to use R 3.6 and install rgeoda 0.0.4. Thanks!

**Comment by lixun910** [comment]
@DrNJT  I am still working on getting rgeoda in CRAN. But, I have current version 0.0.4 available for you to compile and install from source. Could you try it and let me know if it works? Thanks!

**Comment by DrNJT** [comment]
@lixun910 Yes it seems to compile OK under RStudio 1.3.1093 running R 4.0.3 on Ubuntu 18.04

**Comment by DrNJT** [comment]
Happy to close the issue?
