### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by deblnia** [lixun910/rgeoda#4]
Hi! 
I'm trying to install `rgeoda` to use `spatmap` for Intro to Spatial Data Science, but I'm getting an install error. 
 
```
> remotes::install_github("lixun910/rgeoda")
#> Downloading GitHub repo lixun910/rgeoda@master
#> 
#>      checking for file ‘/private/var/folders/5g/w1t31h252w31cy0ztgw0bw0c0000gn/T/RtmpD0yCES/remotes220e5fa96fc9/lixun910-rgeoda-c79e951/DESCRIPTION’ ...  ✓  checking for file ‘/private/var/folders/5g/w1t31h252w31cy0ztgw0bw0c0000gn/T/RtmpD0yCES/remotes220e5fa96fc9/lixun910-rgeoda-c79e951/DESCRIPTION’ (344ms)
#>   ─  preparing ‘rgeoda’:
#>      checking DESCRIPTION meta-information ...  ✓  checking DESCRIPTION meta-information
#>   ─  cleaning src
#>   ─  checking for LF line-endings in source and make files and shell scripts
#>   ─  checking for empty or unneeded directories
#>       ─  building ‘rgeoda_0.0.4.tar.gz’
#>      
#> 
#> Error: Failed to install 'rgeoda' from GitHub:
#>   (converted from warning) installation of package '/var/folders/5g/w1t31h252w31cy0ztgw0bw0c0000gn/T//RtmpD0yCES/file220e3538aeef/rgeoda_0.0.4.tar.gz' had non-zero exit status
```
I've tried using `devtools` and `install.packages()` in addition to the above, but it always errors. My session info is below, but is there any reason why this might be? My hunch is that the package hasn't been made available for R version > 3.6 but I'm not sure. Thanks for your help regardless! 

```
> devtools::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 3.6.1 (2019-07-05)
#>  os       macOS Mojave 10.14.6        
#>  system   x86_64, darwin15.6.0        
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       America/New_York            
#>  date     2020-12-11                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date       lib source        
#>  assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.6.0)
#>  callr         3.4.3   2020-03-28 [1] CRAN (R 3.6.2)
#>  cli           2.2.0   2020-11-20 [1] CRAN (R 3.6.2)
#>  crayon        1.3.4   2017-09-16 [1] CRAN (R 3.6.0)
#>  desc          1.2.0   2018-05-01 [1] CRAN (R 3.6.0)
#>  devtools      2.2.2   2020-02-17 [1] CRAN (R 3.6.0)
#>  digest        0.6.27  2020-10-24 [1] CRAN (R 3.6.2)
#>  ellipsis      0.3.1   2020-05-15 [1] CRAN (R 3.6.2)
#>  evaluate      0.14    2019-05-28 [1] CRAN (R 3.6.0)
#>  fansi         0.4.1   2020-01-08 [1] CRAN (R 3.6.0)
#>  fs            1.5.0   2020-07-31 [1] CRAN (R 3.6.2)
#>  glue          1.4.2   2020-08-27 [1] CRAN (R 3.6.2)
#>  highr         0.8     2019-03-20 [1] CRAN (R 3.6.0)
#>  htmltools     0.4.0   2019-10-04 [1] CRAN (R 3.6.0)
#>  knitr         1.28    2020-02-06 [1] CRAN (R 3.6.0)
#>  magrittr      2.0.1   2020-11-17 [1] CRAN (R 3.6.2)
#>  memoise       1.1.0   2017-04-21 [1] CRAN (R 3.6.0)
#>  pkgbuild      1.0.6   2019-10-09 [1] CRAN (R 3.6.0)
#>  pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.6.0)
#>  prettyunits   1.1.1   2020-01-24 [1] CRAN (R 3.6.0)
#>  processx      3.4.2   2020-02-09 [1] CRAN (R 3.6.0)
#>  ps            1.3.2   2020-02-13 [1] CRAN (R 3.6.0)
#>  R6            2.5.0   2020-10-28 [1] CRAN (R 3.6.2)
#>  Rcpp          1.0.5   2020-07-06 [1] CRAN (R 3.6.2)
#>  remotes       2.1.1   2020-02-15 [1] CRAN (R 3.6.0)
#>  rlang         0.4.9   2020-11-26 [1] CRAN (R 3.6.2)
#>  rmarkdown     2.3     2020-06-18 [1] CRAN (R 3.6.2)
#>  rprojroot     2.0.2   2020-11-15 [1] CRAN (R 3.6.2)
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.6.0)
#>  stringi       1.5.3   2020-09-09 [1] CRAN (R 3.6.2)
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 3.6.0)
#>  testthat      2.3.2   2020-03-02 [1] CRAN (R 3.6.0)
#>  usethis       1.6.3   2020-09-17 [1] CRAN (R 3.6.2)
#>  withr         2.3.0   2020-09-22 [1] CRAN (R 3.6.2)
#>  xfun          0.12    2020-01-13 [1] CRAN (R 3.6.0)
#>  yaml          2.2.1   2020-02-01 [1] CRAN (R 3.6.0)
#> 
#> [1] /Library/Frameworks/R.framework/Versions/3.6/Resources/library
```

**Comment by lixun910** [comment]
@deblnia Yes, the current rgeoda 0.0.4/3 is only for R 3.6 (if I remember correctly). Now, I am working on getting rgeoda 0.1 into CRAN, so there will be no installation issue. It could take a couple of weeks, and I will post updates here. For a workaround, you can try to use R 3.6 and install rgeoda 0.0.4. Thanks!

**Comment by Jakub-42** [comment]
Hi, I changed the R version to 3.6 but still I got 

** using staged installation
** libs
rm -f rgeoda.so ./libgeoda_src/libgeoda.o ./libgeoda_src/pg/geoms.o ./libgeoda_src/pg/utils.o ./libgeoda_src/shapelib/dbfopen.o ./libgeoda_src/shapelib/safileio.o ./libgeoda_src/shapelib/shpopen.o ./libgeoda_src/weights/PointsToContigWeights.o rcpp_rgeoda.o rcpp_weights.o RcppExports.o
make: *** No rule to make target `libgeoda_src/libgeoda.o', needed by `rgeoda.so'.  Stop.
ERROR: compilation failed for package ‘rgeoda’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/rgeoda’
Error: Failed to install 'rgeoda' from GitHub:
  (converted from warning) installation of package ‘/var/folders/3m/3y4rkkh55c577nxghnx9h4wm0000gn/T//Rtmpyw3h0Q/file93943d5c820/rgeoda_0.0.4.tar.gz’ had non-zero exit status


sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.15.7

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.0 tools_3.6.0    remotes_2.2.0

**Comment by lixun910** [comment]
@deblnia @Jakub-42 I have current version 0.0.6 available for you to compile and install from source. Could you try it and let me know if it works? Thanks!  Btw, I am still working on getting rgeoda in CRAN. I will keep you updated.
